<?php
/**
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */

$targetDirectory = 'output';
if (!file_exists( $targetDirectory )) {
    mkdir( $targetDirectory );
}

foreach (glob( "RST/*.rst" ) as $rstFilePath) {
    $pageDirectoryPath = $targetDirectory . '/' . computeDirectory( $rstFilePath );
    @mkdir( $pageDirectoryPath, 0775, true );

    $filename = computeFilename( $rstFilePath );
    if ( $filename === false ) {
        echo "Unable to compute the filename for '$rstFilePath''\n";
        continue;
    }
    $contents = file_get_contents( $rstFilePath );
    fixupSplittedLines( $contents );
    fixupToc( $contents );
    fixupCreatedBy( $contents );
    fixupGeneratedBy( $contents );
    $targetPath = "$pageDirectoryPath/$filename";
    file_put_contents( $targetPath, $contents );
    echo "- $targetPath\n";
}

function computeDirectory( $rstFilePath )
{
    $lines = file( $rstFilePath );

    // We don't need the first 3 lines
    array_shift( $lines );
    array_shift( $lines );
    array_shift( $lines );

    $pathArray = [];
    foreach ($lines as $line) {
        // we stop when done with this initial list
        if ( $line{0} != '#' ) break;
        if ( preg_match( '/#\. \`([^<]+) \<(.*)\>\`__$/', $line, $m ) ) {
            $pathArray[] = str_replace( ' ', '_', strtolower( $m[1] ) );
        }
    }

    $path = fixupMultipleSpaces( strtolower( implode( '/', $pathArray ) ) );
    $path = str_replace( '&', 'and', $path );
    return $path;
}

function computeFilename( $path )
{
    $filename = strtolower( basename( $path, '.html.rst' ) );
    if ( preg_match( '/^(.*)_[0-9]+$/', $filename, $m ) ) {
        $title = $m[1];
    } else {
        $title = figureOutTitle( $path );
        if ($title === false) {
            return false;
        }
    }

    $title = fixupMultipleSpaces( $title );
    $title = str_replace( '&', 'and', $title );
    return strtolower( str_replace( ['-', ' '], '_', $title ) ) . '.rst';
}

function fixupSplittedLines( &$text )
{
    $text = preg_replace( '/([ ]+)-([ ]+)`([^`]+)\n[ ]+([^`]+)`__/m', '\1-\2`\3 \4`__', $text );
}

function figureOutTitle( $path )
{
    $contents = file_get_contents( $path );
    if ( preg_match( '/([^\n]*)\n=={4,}/s', $contents, $m ) ) {
        return str_replace(
            ['eZ Publish Platform 5.x : ', '\\', ':'],
            '',
            $m[1]
        );

    } else {
        return false;
    }
}

function fixupToc( &$text )
{
    $text = preg_replace( '/(\s*-  (`[^\n]+`__[\n]{1,2}))+/m', "\n\n.. contents::\n\n", $text );
}

function fixupCreatedBy( &$text )
{
    $text = preg_replace( '/\nCreated by ([^\s]* .*)\n?(.*)\n+/m', '', $text );
}

function fixupGeneratedBy( &$text )
{
    $text = preg_replace( '/^Document generated by Confluence on .*$/', '', $text );
}

function fixupMultipleSpaces( $text )
{
    return preg_replace( "/(\r\n|\r|\n){2,}/", "\n", $text );
}
